apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-node-cloudwatch
  namespace: kube-system
  labels:
    app: kube-node-cloudwatch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-node-cloudwatch
  namespace: kube-system
  labels:
    app: kube-node-cloudwatch
roleRef:
  kind: ClusterRole
  name: kube-node-cloudwatch
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: "kube-system"
  name: kube-node-cloudwatch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-node-cloudwatch
  namespace: kube-system
  labels:
    app: kube-node-cloudwatch
    chart: kube-spot-termination-notice-handler
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-node-cloudwatch
  namespace: kube-system
  labels:
    k8s-app: kube-node-cloudwatch
spec:
  selector:
    matchLabels:
      name: kube-node-cloudwatch
  template:
    metadata:
      labels:
        name: kube-node-cloudwatch
    spec:
      serviceAccountName: kube-node-cloudwatch
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kube-node-cloudwatch
        image: quay.io/ssuareza/kube-node-cloudwatch:latest
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 30
